name: Build-caddy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install go
      uses: actions/setup-go@master
    
    - name: Install xcaddy
      run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
    
    - name: Build caddy
      run: |
        ~/go/bin/xcaddy build \
          --with github.com/mholt/caddy-l4 \
          --with github.com/mholt/caddy-dynamicdns \
          --with github.com/caddy-dns/alidns \
          --with github.com/caddy-dns/cloudflare \
          --with github.com/caddy-dns/dnspod \
          --with clevergo.tech/caddy-dnspodcn \
          --with github.com/caddy-dns/duckdns \
          --with github.com/mastercactapus/caddy2-proxyprotocol \
          --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive \
          --with github.com/imgk/caddy-trojan@509ea098182a5d3a0e9a0e3a5417b1b25ea15c40 \
          --with github.com/mholt/caddy-webdav
    
    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: caddy-linux-amd64
        path: ./caddy
